### PR TITLE
Fix: Use `nanonid/non-secure` instead of `cuid`

### LINKED ISSUE #1737: Update `cuid` to `paralleldrive/cuid2`
Ref: Screenshot 2023-03-09 at 11 09 00 AM

and 

https://github.com/mui/mui-toolpad/pull/1700#issuecomment-1460534989

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Closes #1737

### CODE REVIEW

**Comment by bharatkashyap** [comment]
@Janpot https://app.circleci.com/pipelines/github/mui/mui-toolpad/6991/workflows/e354df79-c205-4539-a273-61fc4dfb4023/jobs/30387 Is it apparent to you why this test is failing - I can't see why this fails

File: packages/toolpad-app/src/appDom/index.ts [hunk 1]
```diff
@@ -235,7 +237,7 @@ function assertIsType<T extends AppDomNode>(node: AppDomNode, type: T['type']):
 }
 
 function createId(): NodeId {
```
Comment (Janpot) [inline packages/toolpad-app/src/appDom/index.ts:239]:
```tsx
import { init } from '@paralleldrive/cuid2';

const createIdInternal = init({ length: 7 })

export function createId(): NodeId {
  return createIdInternal() as NodeId;
}

File: packages/toolpad-app/src/server/localMode.ts [hunk 2]
```diff
@@ -1077,7 +1077,7 @@ async function initToolpadFolder(root: string) {
       apiVersion: 'v1',
       kind: 'page',
       spec: {
-        id: cuid.slug(),
+        id: cuid2({ length: appDom.SLUG_LENGTH })(),
```
Comment (Janpot) [inline packages/toolpad-app/src/server/localMode.ts:1080]:
```suggestion
        id: appDom.createId(),
```

File: packages/toolpad-app/src/appDom/index.ts (hunk 1 above)
Comment (bharatkashyap) [reply packages/toolpad-app/src/appDom/index.ts:239]: This still fails on `yarn test` with the same error as in the CI

Comment (Janpot) [reply packages/toolpad-app/src/appDom/index.ts:239]: yes, I wasn't proposing this as a fix for that, just as a suggestion to use the lib in a more idiomatic way.

Let's just move to `nanoid/non-secure` instead of `cuid2`. That's more than suitable for our needs and won't have these issues

**Review by Janpot — APPROVED** [review]
