### PR TITLE
Polish Markdown component

### LINKED ISSUE #1470: Polish markdown component
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Open https://master--toolpad.mui.com/deploy/cl6rqzry10009arlv9sto6qja/pages/e943n9y

### Current behavior 😯

- There is a margin around the markdown.
- The `<a>` isn't rendered with the `<Link>` of Material UI.

Screenshot 2022-12-19 at 12 16 23

### Expected behavior 🤔

The opposite.

Screenshot 2022-12-19 at 12 16 52

### Context 🔦

I'm updating some of the Toolpad app we use for the support to use markdown. Related to #1298.

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Closes #1470 
- Visual demonstration 
- Replace `react-markdown` with `markdown-to-jsx`
- Uses Material UI `Link` instead of `a`
- Links open in new tabs through `target=_blank`
- No margin

https://user-images.githubusercontent.com/19550456/208647318-f51dd1bc-d329-4a57-a1c7-c904f788117b.mov

### CODE REVIEW

File: packages/toolpad-components/src/Text.tsx [hunk 1]
```diff
@@ -34,7 +33,21 @@ function Text({ value, markdown, href, loading, mode, sx, ...rest }: TextProps)
...
           <React.Suspense>
-            <ReactMarkdown remarkPlugins={[remarkGfm]}>{value}</ReactMarkdown>
+            <ReactMarkdown
+              options={{
+                overrides: {
+                  a: {
+                    component: MuiLink,
+                    props: {
+                      target: '_blank',
+                      rel: 'noopener noreferrer nofollow',
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:43]: I think that we could let the search engine crawler follow and crawl these links, and be a bit less opinionated https://ahrefs.com/blog/nofollow-links/. If people want to prevent it, they could write a full `<a href` element.

```suggestion
                      rel: 'noopener noreferrer',
```

File: packages/toolpad-components/src/Text.tsx [hunk 2]
```diff
@@ -34,7 +33,21 @@ function Text({ value, markdown, href, loading, mode, sx, ...rest }: TextProps)
       ) : (
         <MarkdownContainer>
           <React.Suspense>
-            <ReactMarkdown remarkPlugins={[remarkGfm]}>{value}</ReactMarkdown>
+            <ReactMarkdown
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:36]: We need the markdown component to have a min-height when it's empty so that developers can make changes.

Screenshot 2022-12-20 at 11 43 16

Comment (oliviertassinari) [reply packages/toolpad-components/src/Text.tsx:36]: We might want to handle `<code><pre>` and `<code>`. 

Screenshot 2022-12-20 at 11 45 06

Comment (oliviertassinari) [reply packages/toolpad-components/src/Text.tsx:36]: To see if the ids can break toolpad

Screenshot 2022-12-20 at 11 44 57

**Comment by bharatkashyap** [comment]
Review feedback: 

Screenshot 2023-01-03 at 3 49 47 PM

File: packages/toolpad-components/src/Text.tsx [hunk 3]
```diff
@@ -34,7 +42,25 @@ function Text({ value, markdown, href, loading, mode, sx, ...rest }: TextProps)
...
+                    props: {
+                      target: '_blank',
+                      rel: 'noopener noreferrer',
+                    },
+                  },
+                  pre: {
+                    component: CodeContainer,
+                  },
+                },
+                slugify: (text) => `toolpad-markdown-${text}`,
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:59]: But this would turn the links into `#toolpad-markdown-my-id`

File: packages/toolpad-components/src/Text.tsx [hunk 4]
```diff
@@ -23,9 +22,18 @@ interface TextProps extends Omit<BaseProps, 'children'> {
 
 const MarkdownContainer = styled('div')({
   display: 'block',
-  [`&:empty::before`]: { content: '""', display: 'inline-block' },
+  minHeight: '25px',
 });
 
+const CodeContainer = styled('pre')(({ theme }) => ({
+  whiteSpace: 'pre-wrap',
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:29]: Most code doesn't look great when wrapped. Can't we handle this using overflow?

File: packages/toolpad-components/src/Text.tsx [hunk 5]
```diff
@@ -23,9 +22,18 @@ interface TextProps extends Omit<BaseProps, 'children'> {
 
 const MarkdownContainer = styled('div')({
   display: 'block',
-  [`&:empty::before`]: { content: '""', display: 'inline-block' },
+  minHeight: '25px',
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:25]: I'd prefer this to be solved using a similar trick as the `&:empty::before` so that it follows `fontSize` rather than an absolute height

File: packages/toolpad-components/src/Text.tsx [hunk 6]
```diff
@@ -8,9 +8,8 @@ import {
   styled,
 } from '@mui/material';
 import { createComponent } from '@mui/toolpad-core';
-import remarkGfm from 'remark-gfm';
 
-const ReactMarkdown = React.lazy(() => import('react-markdown'));
+const ReactMarkdown = React.lazy(() => import('markdown-to-jsx'));
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:12]:
```suggestion
const Markdown = React.lazy(() => import('markdown-to-jsx'));
```
Let's rename to just `Markdown` now that we don't use `react-markdown` anymore?

File: packages/toolpad-components/src/Text.tsx (hunk 4 above)
Comment (bharatkashyap) [reply packages/toolpad-components/src/Text.tsx:29]: `white-space: pre-wrap` 
> Sequences of white space are preserved. Lines are broken at newline characters, at `<br>`, and as necessary to fill line boxes.

solves the problem acceptably well in most code snippets I tried.

File: packages/toolpad-components/src/Text.tsx (hunk 3 above)
Comment (oliviertassinari) [reply packages/toolpad-components/src/Text.tsx]: > When is id a problem exactly?

No idea. I left the feedback in case we rely on `getElementById`. If we don't, I think that keeping the id is simpler.

File: packages/toolpad-components/src/Text.tsx [hunk 7]
```diff
@@ -23,9 +22,22 @@ interface TextProps extends Omit<BaseProps, 'children'> {
 
 const MarkdownContainer = styled('div')({
   display: 'block',
-  [`&:empty::before`]: { content: '""', display: 'inline-block' },
+  maxWidth: 'fill-available',
+  '& span:empty::before': {
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:26]: So that the min-height triggers when the lazy import is resolving?

```suggestion
  '&:empty::before, & span:empty::before': {
```

Comment (oliviertassinari) [reply packages/toolpad-components/src/Text.tsx:26]: Also, we don't want to trigger `<span>` that are rendered by the markdown, so only the first direct children

```suggestion
  '&:empty::before, & > span:empty::before': {
```

File: packages/toolpad-components/src/Text.tsx [hunk 8]
```diff
@@ -23,9 +22,22 @@ interface TextProps extends Omit<BaseProps, 'children'> {
...
 });
 
+const CodeContainer = styled('pre')(({ theme }) => ({
+  backgroundColor: theme.palette.grey[200],
+  marginLeft: theme.spacing(1),
+  marginRight: theme.spacing(1),
+  borderRadius: theme.shape.borderRadius,
+  padding: theme.spacing(1),
+  overflowX: 'scroll',
+}));
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:39]: In the future, when we look into performance, we could look if styling `& pre` in the container isn't faster.

File: packages/toolpad-components/src/Text.tsx [hunk 9]
```diff
@@ -23,9 +22,22 @@ interface TextProps extends Omit<BaseProps, 'children'> {
 
 const MarkdownContainer = styled('div')({
   display: 'block',
-  [`&:empty::before`]: { content: '""', display: 'inline-block' },
+  maxWidth: 'fill-available',
+  '& span:empty::before': {
+    content: '""',
+    display: 'inline-block',
+  },
 });
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:30]: I think that it would be good to remove the margin top and bottom. It looks like Retool had the same idea:

Screenshot 2023-01-09 at 00 41 50
Screenshot 2023-01-09 at 00 41 58

The problem right now is that

```
foo

bar
```

renders like this:

Screenshot 2023-01-09 at 00 43 18

File: packages/toolpad-components/src/Text.tsx [hunk 10]
```diff
@@ -23,9 +22,22 @@ interface TextProps extends Omit<BaseProps, 'children'> {
...
 
+const CodeContainer = styled('pre')(({ theme }) => ({
+  backgroundColor: theme.palette.grey[200],
+  marginLeft: theme.spacing(1),
+  marginRight: theme.spacing(1),
+  borderRadius: theme.shape.borderRadius,
+  padding: theme.spacing(1),
+  overflowX: 'scroll',
```
Comment (oliviertassinari) [inline packages/toolpad-components/src/Text.tsx:38]: overflow scroll is very rarely helpful because it always shows the scrollbar, e.g.

Screenshot 2023-01-09 at 00 47 07

So:

```suggestion
  overflow: 'auto',
```

**Review by oliviertassinari — COMMENTED** [review]
I think that we have room to do a lot of polish on the rendering (we did a lot for mui.com's docs). I have left feedback on what seems to be the most important. I think that it's good enough 👍, we have enough for the community to leave feedback on what to improve, next problem 😁

> markdown-to-jsx is very popular, but who is it losing market share to?

@Janpot I can't find anything obvious.

File: packages/toolpad-components/src/Text.tsx (hunk 9 above)
Comment (bharatkashyap) [reply packages/toolpad-components/src/Text.tsx:30]: I don't see any margin on the markdown element: 
Screenshot 2023-01-09 at 6 25 19 PM

Comment (Janpot) [reply packages/toolpad-components/src/Text.tsx:31]: I think it's [collapsed](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing) from the one in the paragraphs

File: packages/toolpad-components/src/Text.tsx [hunk 11]
```diff
@@ -35,14 +34,28 @@ const gutters = (marginTop: number, marginBottom: number) => ({
...
   display: 'block',
-  [`&:empty::before`]: { content: '""', display: 'inline-block' },
-  h1: { ...theme.typography.h1, ...gutters(16, 16) },
-  h2: { ...theme.typography.h2, ...gutters(12, 12) },
-  h3: { ...theme.typography.h3, ...gutters(12, 12) },
-  h4: { ...theme.typography.h4, ...gutters(12, 12) },
-  h5: { ...theme.typography.h5, ...gutters(4, 4) },
-  h6: { ...theme.typography.h6, ...gutters(4, 4) },
-  p: { margin: 0, marginBottom: 6 },
+  maxWidth: 'fill-available',
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:37]:
```suggestion
```

This doesn't seem to do anything for me. Which situation is this olving?

Comment (bharatkashyap) [reply packages/toolpad-components/src/Text.tsx:37]: This is to introduce scrollbars in content that spans the width of the container:

Without `fill-available`:
Screenshot 2023-02-16 at 5 19 12 PM

With:
Screenshot 2023-02-16 at 5 19 29 PM

Comment (Janpot) [reply packages/toolpad-components/src/Text.tsx:37]: Oh, ok, I see. Does it have advantages over `maxWidth: '100%'`?

Comment (bharatkashyap) [reply packages/toolpad-components/src/Text.tsx:37]: Nothing specifically I guess, I can use `100%` as well

**Review by Janpot — APPROVED** [review]

File: packages/toolpad-components/src/Text.tsx [hunk 12]
```diff
@@ -34,8 +34,10 @@ const gutters = (marginTop: number, marginBottom: number) => ({
 
 const MarkdownContainer = styled('div')(({ theme }) => ({
   display: 'block',
-  maxWidth: 'fill-available',
-
+  maxWidth: '100%',
+  '&  p': {
```
Comment (Janpot) [inline packages/toolpad-components/src/Text.tsx:38]: There's already a rule for this

**Review by Janpot — CHANGES_REQUESTED** [review]

**Review by Janpot — APPROVED** [review]
