### PR TITLE
[cli] Clean templates, fix a bunch of issues in generated apps

### LINKED ISSUE #3972: create-toolpad-app: add warning on missing configuration
### Summary

We could add a warning, or even crash the program on missing required configuration.

### Examples

e.g. User configures Google authentication but forgets to configure the variables. We could add something like the following in the `auth.js` file:

```tsx
invariant(process.env.GOOGLE_CLIENT_ID, 'GOOGLE_CLIENT_ID is required. See https://mui.com/auth/google');
invariant(process.env.GOOGLE_CLIENT_SECRET, 'GOOGLE_CLIENT_SECRET is required. See https://mui.com/auth/google');
```

### Motivation

Early warning when user tries to start a program that can't be accessed. Early fail when user tries to deploy without configuring these variables.

**Search keywords**: config warning

### LINKED ISSUE #3973: create-toolpad-app: align created apps content
### Steps to reproduce

Create an app with authentication, without authentication app router and pages router.

### Current behavior

The apps have different routing structure and page content.

### Expected behavior

The apps look functionally identical.

when no authentication is configured, there is this / and /page routes that don't exist when no authentication is configured

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: create-toolpad-app

### LINKED ISSUE #4005: [create-toolpad-app] Issues with pages router app
### Steps to reproduce

Steps:
1. Run `pnpm create toolpad-app`
2. Type dir `repro`
3. choose pages router
4. choose no authentication
5. `cd repro`
6. `pnpm dev`
7. open application

### Current behavior

* The title and logo are misaligned:
    Screenshot 2024-08-28 at 12 32 57

* There is an error logged in the console:
    ```
    hydration-error-info.js:63 Warning: Failed prop type: The following props are not supported: `documentNode`, `colorSchemeNode`, `disableNestedContext`, `colorSchemeStorageKey`, `modeStorageKey`. Please remove them.
        at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+system@5.16.7_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@1_itqvvhqn72zk5isxntjqjwq4yi/node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:58:5)
        at ThemeProvider (webpack-internal:///./node_modules/.pnpm/@mui+material@5.16.7_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled_u54plt3h22lcxai37fz66nmgt4/node_modules/@mui/material/styles/ThemeProvider.js:26:18)
        at LegacyThemeProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppThemeProvider.js:44:5)
        at AppThemeProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppThemeProvider.js:127:5)
        at AppProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/AppProvider/AppProvider.js:58:5)
        at AppProviderNextPages (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/nextjs/AppProviderNextPages.js:26:64)
        at AppProvider (webpack-internal:///./node_modules/.pnpm/@toolpad+core@0.5.2_@emotion+react@11.13.3_@types+react@18.3.4_react@18.3.1__@emotion+styled@_nvqt2dlcvjyyhbimkqaqd6jpaa/node_modules/@toolpad/core/nextjs/AppProvider.js:23:81)
        at AppLayout (webpack-internal:///./pages/_app.tsx:76:11)
        at AppCacheProvider (webpack-internal:///./node_modules/.pnpm/@mui+material-nextjs@5.16.6_@emotion+cache@11.13.1_@emotion+server@11.11.0_@mui+material@5.16_gstiav3gveww4whjxphmrxwv5a/node_modules/@mui/material-nextjs/v13-pagesRouter/pagesRouterV13App.js:17:3)
        at App (webpack-internal:///./pages/_app.tsx:112:13)
        at PathnameContextProviderAdapter (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/shared/lib/router/adapters.js:81:11)
        at ErrorBoundary (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/pages/ErrorBoundary.js:41:9)
        at ReactDevOverlay (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/components/react-dev-overlay/pages/ReactDevOverlay.js:33:11)
        at Container (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:81:1)
        at AppContainer (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:189:11)
        at Root (webpack-internal:///./node_modules/.pnpm/next@14.2.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/client/index.js:413:11)
    ```

### Expected behavior

_No response_

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: create-toolpad-app pages router

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Fixes #4005 
- Fixes #3973 
- Fixes #3972 

- Also cleans up the template files to have one file per "file type" to avoid duplication
- Also brings the playground apps in line with the generated templates
- Also brings the example apps in line with the generated templates
- Also makes a small change to the `SignInPage` to better support longer app names

### CODE REVIEW

File: examples/core-auth-nextjs-pages/src/pages/_app.tsx [hunk 1]
```diff
@@ -40,7 +39,7 @@ const NAVIGATION: Navigation = [
 ];
 
 const BRANDING = {
-  title: 'My Toolpad Core App',
+  title: 'My Toolpad Core Next.js Pages App',
```
Comment (Janpot) [inline examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: I wouldn't do this.

Comment (bharatkashyap) [reply examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: It makes the app easier to identify while testing/running - in all likelihood a person running this example is going to change these anyway regardless of whatever the default text is

File: packages/create-toolpad-app/src/templates/auth/auth.ts [hunk 2]
```diff
@@ -18,7 +18,33 @@ const CredentialsProviderTemplate = `Credentials({
...
+if (!process.env.${kebabToConstant(provider)}_CLIENT_SECRET) {
+  missingVars.push('${kebabToConstant(provider)}_CLIENT_SECRET');
+}`,
+  )
+  .join('\n')}
+
+if (missingVars.length > 0) {
+  const baseMessage = 'Authentication is configured but the following environment variables are missing:';
+  
+  if (process.env.NODE_ENV === 'production') {
```
Comment (Janpot) [inline packages/create-toolpad-app/src/templates/auth/auth.ts:39]: Avoid different behavior in dev vs. prod. If it crashes in prod it must crash in dev. Let's just warn then.


I'd suggest to start by just generating the following code
```tsx
function warnOnMissing(var: string, provider: string, name: string) {
  if (!var) {
    console.warn(`${provider} provider: environment variable "${name}" missing`);
  }
}

warnOnMissing(process.env.GOOGLE_CLIENT_ID, 'Google', 'GOOGLE_CLIENT_ID')
warnOnMissing(process.env.GOOGLE_CLIENT_SECRET, 'Google', 'GOOGLE_CLIENT_SECRET')
// ...
```

File: packages/create-toolpad-app/src/templates/indexPage.ts [hunk 3]
```diff
@@ -0,0 +1,46 @@
+import { SupportedRouter } from '../types';
+
+const indexPage = (authEnabled: boolean, routerType: SupportedRouter) => {
```
Comment (Janpot) [inline packages/create-toolpad-app/src/templates/indexPage.ts:3]: Can't we just give all templates the same options as an object? That way we only have to create that once and can pass it to each template.

File: examples/core-auth-nextjs-pages/src/pages/_app.tsx (hunk 1 above)
Comment (Janpot) [reply examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: > It makes the app easier to identify while testing/running

Sure, but that's not a problem our users would have. We can't do it for all permutations, so I propose we do it for none.

Comment (bharatkashyap) [reply examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: I propose we only do it for things that aren't immediately visible on the app (Auth providers/Theme/Branding are all visible and obvious). Currently it would only be the type of router; if we introduce something that fits this criteria in the future, we could do it for that as well

Comment (apedroferreira) [reply examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: The previous title was already looking a bit too long for the current layout, I would also prefer to use shorter titles...

File: playground/nextjs-pages/src/pages/_app.tsx [hunk 4]
```diff
@@ -27,6 +27,7 @@ const NAVIGATION: Navigation = [
     title: 'Main items',
   },
   {
+    segment: '',
```
Comment (apedroferreira) [inline playground/nextjs-pages/src/pages/_app.tsx:30]: The default `segment` is already `''` so we don't need to include it.

File: examples/core-auth-nextjs-pages/src/pages/_app.tsx (hunk 1 above)
Comment (bharatkashyap) [reply examples/core-auth-nextjs-pages/src/pages/_app.tsx:42]: Removed the longer titles

**Review by apedroferreira — APPROVED** [review]
