### PR TITLE
fix it will be reset the value and fix 404

### LINKED ISSUE #2648: Previewing the movies static json fails in a fresh app
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. Run the default HTTP request

Screenshot 2023-09-08 at 1 29 32 PM

### Current behavior 😯

_No response_

### Expected behavior 🤔

_No response_

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  System:
    OS: macOS 13.3
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Edge: Not Found
    Safari: 16.4
  npmPackages:
    @emotion/react:  11.11.1 
    @emotion/styled:  11.11.0 
    @mui/base:  5.0.0-beta.14 
    @mui/core-downloads-tracker:  5.14.8 
    @mui/icons-material:  5.14.8 
    @mui/lab:  5.0.0-alpha.143 
    @mui/material:  5.14.8 
    @mui/private-theming:  5.14.8 
    @mui/styled-engine:  5.14.8 
    @mui/system:  5.14.8 
    @mui/toolpad: ^0.1.27 => 0.1.27 
    @mui/toolpad-components:  0.1.27 
    @mui/toolpad-core:  0.1.27 
    @mui/toolpad-utils:  0.1.27 
    @mui/types:  7.2.4 
    @mui/utils:  5.14.8 
    @mui/x-data-grid:  6.12.1 
    @mui/x-data-grid-pro:  6.12.1 
    @mui/x-date-pickers:  6.12.1 
    @mui/x-date-pickers-pro:  6.12.1 
    @mui/x-license-pro:  6.10.2 
    @mui/x-tree-view:  6.0.0-alpha.1 
    @types/react:  18.2.21 
    react:  18.2.0 
    react-dom:  18.2.0 
    typescript:  5.2.2 
```
</details>

### PR DESCRIPTION
**Pull request by JerryWu1234**
Fixes #2648 
- [x] I've read and followed the [contributing guide](https://github.com/mui/mui-toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [x] I've updated the relevant documentation for any new or updated feature
- [x] I've linked relevant GitHub issue with "Closes #<issue id>"
- [x] I've added a visual demonstration under the form of a screenshot or video

### CODE REVIEW

**Comment by JerryWu1234** [comment]
image

**Comment by JerryWu1234** [comment]
image

File: packages/toolpad-app/src/toolpadDataSources/rest/client.tsx [hunk 1]
```diff
@@ -256,9 +256,11 @@ function QueryEditor({
 
   const connectionParams = isBrowserSide ? null : rawConnectionParams;
   const baseUrl = isBrowserSide ? null : connectionParams?.baseUrl ?? null;
-
+  // input.attributes.query.url will be reset when it's empty
   const urlValue: BindableAttrValue<string> =
```
Comment (Janpot) [inline packages/toolpad-app/src/toolpadDataSources/rest/client.tsx:260]: Alternatively, I believe this could be written as
```tsx
  const urlValue: BindableAttrValue<string> =
    input.attributes.query.url ?? getDefaultUrl(config, connectionParams);
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

**Comment by JerryWu1234** [comment]
I will fix it when you review over.

File: packages/toolpad-app/src/server/localMode.ts [hunk 2]
```diff
@@ -989,11 +989,16 @@ class ToolpadProject {
 
   private pendingVersionCheck: Promise<VersionInfo> | undefined;
 
-  constructor(root: string, options: Partial<ToolpadProjectOptions>) {
+  constructor(
+    root: string,
+    options: Partial<ToolpadProjectOptions>,
+    externalUrl: string = 'http://localhost:3000',
```
Comment (Janpot) [inline packages/toolpad-app/src/server/localMode.ts:995]: Let's put `externalUrl` in the options, as per https://github.com/mui/mui-toolpad/issues/2648#issuecomment-1721312565

**Review by Janpot — CHANGES_REQUESTED** [review]
Two small changes and then this is good to go

File: packages/toolpad-app/src/server/localMode.ts (hunk 2 above)
Comment (JerryWu1234) [reply packages/toolpad-app/src/server/localMode.ts:995]: image
image

Follow your step, there is a problem, if it doesn't set a default value.

Comment (Janpot) [reply packages/toolpad-app/src/server/localMode.ts:995]: I don't believe your screenshot corresponds to https://github.com/mui/mui-toolpad/issues/2648#issuecomment-1721312565

Comment (JerryWu1234) [reply packages/toolpad-app/src/server/localMode.ts:995]: image

you pass to `ToolpadProject`, so that we need to receive a `externalUrl`

and we can't directly pass to the `options` because  the `externalUrl` maybe is  `undefined `

image

Comment (JerryWu1234) [reply packages/toolpad-app/src/server/localMode.ts:995]: image

Comment (Janpot) [reply packages/toolpad-app/src/server/localMode.ts:995]: It's being passed to the `ToolpadProject` as a `externalUrl` property of the second parameter `options`. Not as a third parameter `externalUrl`

Comment (JerryWu1234) [reply packages/toolpad-app/src/server/localMode.ts:995]: my bad, i'm sory. I'll fix it. lol

**Review by Janpot — APPROVED** [review]
Thank you!
