### PR TITLE
[sheets] Ability to let user set named columns in API response

### LINKED ISSUE #310: [sheets] Handle empty columns in Datagrids
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

image
image

### Expected behavior 🤔

The Datagrid should ignore empty columns in the query state data

### Steps to reproduce 🕹

Steps:

1. Create a Google Sheets API
2. Connect to a Sheet
3. Create a Query State containing the Sheets API data
4. Create a Datagrid and bind it to the above Query State

### Context 🔦

_No response_

### Your environment 🌎

https://toolpad-pr-236.onrender.com/app/cl280m3j30003a1kpalmidzdy/1/pages/cl281we3j00013f675rer18yv

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Fixes #310 

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

File: packages/toolpad-components/src/DataGrid.tsx [hunk 1]
```diff
@@ -144,6 +144,7 @@ const DataGridComponent = React.forwardRef(function DataGridComponent(
         onColumnOrderChange={handleColumnOrderChange}
         rows={rows}
         columns={columns}
+        getRowId={(row) => row.id ?? crypto.getRandomValues(new Uint16Array(1))[0]}
```
Comment (Janpot) [inline packages/toolpad-components/src/DataGrid.tsx:147]:
```suggestion
```
Let's not make it part of  this PR. I'll leave some comments on the issue you created

File: packages/toolpad-app/src/toolpadDataSources/googleSheets/types.ts [hunk 2]
```diff
@@ -31,6 +31,11 @@ export type GoogleSheetsApiQuery = {
    * The sheet to request.
    */
   sheetName: GoogleSheetProperties['title'];
+  /**
+   * Whether to transform the response assuming
+   * the first row to be column headers
+   */
+  transformResponse: boolean;
```
Comment (Janpot) [inline packages/toolpad-app/src/toolpadDataSources/googleSheets/types.ts:38]: Let's be a bit more descriptive

```suggestion
  firstRowAreHeaders: boolean;
```

**Review by Janpot — APPROVED** [review]

**Comment by bharatkashyap** [comment]
To merge after #340 is merged
