### PR TITLE
[cli] Fix core example 

### LINKED ISSUE #3846: [core] Unable to run the tutorial after installing (using npm)
### Steps to reproduce

Steps:
1. Follow instructions from: https://mui.com/toolpad/core/introduction/tutorial/

### Current behavior

Terminal output

```
prakhargupta@Prakhars-MacBook-Pro tutorial % npx create-toolpad-app@latest --example core-tutorial
Need to install the following packages:
create-toolpad-app@0.4.0
Ok to proceed? (y) y
? Enter path for new project directory: my-app

info - Downloading example "core-tutorial" to /Users/prakhargupta/Desktop/tutorial/my-app

Downloading… 194.768 MB
success - Downloaded and extracted "core-tutorial" to /Users/prakhargupta/Desktop/tutorial/my-app

Run the following to get started: 

  cd my-app
  npm run dev

prakhargupta@Prakhars-MacBook-Pro tutorial % cd my-app
prakhargupta@Prakhars-MacBook-Pro my-app % npm run dev

> core-test@0.1.0 dev
> next dev

sh: next: command not found
prakhargupta@Prakhars-MacBook-Pro my-app % npm run dev

> core-test@0.1.0 dev
> next dev

sh: next: command not found
prakhargupta@Prakhars-MacBook-Pro my-app % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: core-test@0.1.0
npm ERR! Found: eslint@9.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^7.23.0 || ^8.0.0" from eslint-config-next@14.2.5
npm ERR! node_modules/eslint-config-next
npm ERR!   dev eslint-config-next@"^14.2.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/prakhargupta/.npm/_logs/2024-07-26T06_32_49_784Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/prakhargupta/.npm/_logs/2024-07-26T06_32_49_784Z-debug-0.log
prakhargupta@Prakhars-MacBook-Pro my-app % npm run dev

> core-test@0.1.0 dev
> next dev

sh: next: command not found
prakhargupta@Prakhars-MacBook-Pro my-app % cd my-app
```
**Note:** Later on, I was able to run `pnpm i` and `pnpm run dev` but the localhost couldn't open the app. I got the following error:

Screenshot 2024-07-26 at 12 13 27 PM

### PR DESCRIPTION
**Pull request by bharatkashyap**
- Fixes #3846 
- Also adds by default installation to the dependencies when an `--example` is passed
- Clean up

### CODE REVIEW

File: packages/create-toolpad-app/src/index.ts [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #!/usr/bin/env node
+/* eslint-disable no-console */
```
Comment (Janpot) [inline packages/create-toolpad-app/src/index.ts:2]: I think we should keep the individual ones

**Review by Janpot — APPROVED** [review]
