### PR TITLE
Components explorer improvements

### LINKED ISSUE #2360: Page hierarchy explorer doesn't always select
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1. build Toolpad `yarn && yarn release:build`
2. start Toolpad dev on the basic backend fixture: `yarn toolpad dev test/integration/backend-basic/fixture`
3. open the "basic" page
4. try selecting items in the page hierarchy explorer

### Current behavior 😯

1. It doesn't always select the item (see video)
2. hovering over page rows doesn't highlight them
3. the title "components" is very ambiguous. Components for me are like templates, they are blueprints. When they're instantiated on the page I prefer to talk about nodes, or elements.

https://github.com/mui/mui-toolpad/assets/2109932/89208dd8-5a26-43ec-9927-36651b9b380a

### Expected behavior 🤔

1. It always selects the node when I click it
2. hovering over page rows highlights the node in the canvas
3. I propose we change the title to "page hierarchy"

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by bharatkashyap**
- [x] I've updated the relevant documentation for any new or updated feature
- Partial of #2360 

https://github.com/mui/mui-toolpad/assets/19550456/a3de96dc-8510-4c01-bb48-2516eda95857

### CODE REVIEW

File: packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx [hunk 1]
```diff
@@ -135,7 +135,12 @@ function RecursiveSubTree({
   }
   if (renderItem.length) {
     return (
-      <TreeItem nodeId={root.id} label={<Typography variant="body2">{root.name}</Typography>}>
+      <CustomTreeItem
+        nodeId={root.id}
+        node={root}
+        label={<Typography variant="body2">{root.name}</Typography>}
+        onHover={onHover}
```
Comment (Janpot) [inline packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx:142]: Forgot `onMouseLeave={onMouseLeave}` here? I feel like there's a lot of duplication in this component and the next developer may forget to pass a new property to every item here.

File: packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx [hunk 2]
```diff
@@ -135,7 +135,12 @@ function RecursiveSubTree({
   }
   if (renderItem.length) {
```
Comment (Janpot) [inline packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx:136]:
```suggestion
  if (renderItem.length > 0) {
```

File: packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx [hunk 3]
```diff
@@ -120,7 +120,7 @@ function RecursiveSubTree({
 
   if (children.length) {
```
Comment (Janpot) [inline packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx:121]: Let's not rely on implicit conversion. 

```suggestion
  if (children.length > 0) {
```

File: packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx (hunk 1 above)
Comment (Janpot) [reply packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx:144]: It feels a bit like there's a lot of duplication in this component that leads to these sort of mistakes. Any way this could be improved?

Comment (bharatkashyap) [reply packages/toolpad-app/src/toolpad/AppEditor/StructureExplorer/index.tsx:144]: I'll look into that as well

**Review by Janpot — APPROVED** [review]
